---

- hosts: all
  become: true
  tasks:
  
  - name: update
    tags: always 
    package:
      update_cache: yes

  - name: create user
    user:
      name: simone
      groups: root

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root 

  - name: install apache and php packages (Ubuntu)
    tags: ubuntu,apache2,php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

