---

- hosts: all
  become: true
  tasks:
  - name: install apache and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
  - name: create html file with network info
    copy:
      dest: /var/www/html/index.html
      content: |
        <!DOCTYPE html>
          <html>
          <head>
              <title>Nebula Cloud Systems</title>
          </head>
          <body> 
              <h1>Welcome Nebula</h1>
              <p>This is the default Website page</p>
          </body>
          </html>
      owner: root
      group: root
      mode: 0644

