---

- hosts: all
  become: true
  vars:
    mysql_root_password: "root111"
    mysql_database_name: "db1"
    mysql_user: "bora"
    mysql_password: "bora111"
    table_name: "users"

  tasks: 
    
  - name: update apt package index
    apt: 
     update_cache: yes

  - name: install mysql server
    apt:
     name: 
       - mysql-server
       - python3-pymysql
     state: present

  - name: ensure mysql service is running
    service:
      name: mysql
      state: started
      enabled: yes

  - name: set mysql root password
    mysql_user:
      name: root
      host: localhost
      password: "{{mysql_root_password}}"
      login_user: root
      login_password: root111
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: present

  - name: remove mysql anonymous user
    mysql_user:
      name: ""
      host: localhost
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: absent

  - name: remove mysql test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: create mysql database
    mysql_db:
      name: "{{ mysql_database_name }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: create mysql user
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}" 
      priv: "{{ mysql_database_name }}.*:ALL"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      state: present

  - name: create table in database
    mysql_query:
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_password }}"
      login_db: "{{ mysql_database_name }}"
      query: |
          CREATE TABLE IF NOT EXISTS {{ table_name }} (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );

  - name: insert to table
    mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database_name }}"
        query: |
          INSERT INTO {{ table_name }} (id,name) VALUES
          (1,'bora'),
          (2,'beril'),
          (3,'tuğkan');

