---
# ---------------------------------------------------------------------------
# Tüm hostlar için geçerli ortak değişkenler
# ---------------------------------------------------------------------------

ansible_user: bora
ansible_ssh_private_key_file: ~/.ssh/ansible
